//! Fixture media for the Red5 interop suite.
//!
//! Red5's live app relays publisher bytes opaquely, so fixtures only need
//! correct FLV tag framing - not decodable pictures. Publish -> play
//! round-trips then prove byte preservation, which is exactly the proxy's
//! contract. Nothing here is generated by an encoder; see README.md.

use bytes::Bytes;
use rtmpx::amf3::Amf3Value;
use rtmpx::sessions::StreamMetadata;

/// onMetaData the harness publishes: legacy AVC + AAC hints.
pub fn legacy_metadata() -> StreamMetadata {
    let mut m = StreamMetadata::new();
    m.video_width = Some(1280);
    m.video_height = Some(720);
    m.video_codec_id = Some(7); // AVC
    m.video_frame_rate = Some(30.0);
    m.audio_codec_id = Some(10); // AAC
    m.audio_sample_rate = Some(44100);
    m.audio_channels = Some(2);
    m.audio_is_stereo = Some(true);
    m.encoder = Some("rtmpx-red5-harness".to_string());
    m
}

/// Legacy AVC sequence header (0x17 0x00) with a plausible
/// AVCDecoderConfigurationRecord. Red5 relays it; the player compares bytes.
pub fn avc_sequence_header() -> Bytes {
    Bytes::from(vec![
        0x17, 0x00, 0x00, 0x00, 0x00, // keyframe, AVC seq header, cts 0
        0x01, 0x64, 0x00, 0x1f, 0xff, 0xe1, 0x00, 0x0b, 0x67, 0x64, 0x00, 0x1f, 0xac, 0xd9, 0x40,
        0x78, 0x02, 0x27, 0xe5, 0x01, 0x01, 0x01, 0x02, 0x68, 0xeb, 0xec, 0xb2, 0x2c,
    ])
}

/// One legacy AVC coded frame (0x17 0x01) with a 4-byte fake NALU.
pub fn avc_coded_frame(nalu_byte: u8) -> Bytes {
    Bytes::from(vec![
        0x17, 0x01, 0x00, 0x00, 0x05, // keyframe, AVC NALU, cts 5
        0x00, 0x00, 0x00, 0x04, // NALU length
        0x65, nalu_byte, 0x88, 0x84, // fake IDR payload
    ])
}

/// AAC sequence header (0xAF 0x00): AudioSpecificConfig for LC 44.1k stereo.
pub fn aac_sequence_header() -> Bytes {
    Bytes::from(vec![0xAF, 0x00, 0x12, 0x10])
}

/// One AAC raw frame (0xAF 0x01) with a 4-byte fake payload.
pub fn aac_raw_frame(fill: u8) -> Bytes {
    Bytes::from(vec![0xAF, 0x01, 0x21, fill, 0x23, 0x24])
}

/// Enhanced RTMP sequence start for HEVC ('hvc1'): 0x12 framing + FourCC.
/// Characterization only - Red5 has no Enhanced media path (see matrix row 5).
pub fn enhanced_hvc1_sequence_start() -> Bytes {
    Bytes::from(vec![
        0x12, b'h', b'v', b'c', b'1', // keyframe, sequence start, FourCC
        0x01, 0x01, 0x60, 0x00, 0x00, 0x00, 0x90, 0x00, 0x00, 0x00, 0x00, 0x00, 0x5d, 0xf0, 0x00,
        0xfc, 0xfd, 0xf8, 0xf8, 0x00, 0x00, 0x0f, 0x03, 0x20, 0x00, 0x01, 0x00, 0x16,
    ])
}

/// Enhanced RTMP coded frame for AV1 ('av01'): 0x10 framing + FourCC + obu.
pub fn enhanced_av1_coded_frame() -> Bytes {
    Bytes::from(vec![
        0x10, b'a', b'v', b'0', b'1', // keyframe, coded frames, FourCC
        0x00, 0x00, 0x05, // composition time offset
        0x0a, 0x0b, 0x00, 0x00, 0x0c, 0x12, 0x00, 0x0a, 0x0a, 0x00, 0xde, 0xad, 0xbe, 0xef,
    ])
}

/// A type-15 (@setDataFrame over AMF3) body carrying a marker field the player
/// asserts on. First payload byte is the 0x03 format selector: AMF3 body.
pub fn amf3_probe_body() -> Bytes {
    let values = vec![
        Amf3Value::String("@setDataFrame".to_string()),
        Amf3Value::String("onMetaData".to_string()),
        Amf3Value::dynamic_object(vec![
            ("rtmpxRed5Probe".to_string(), Amf3Value::Integer(42)),
            (
                "encoder".to_string(),
                Amf3Value::String("rtmpx-red5-harness-amf3".to_string()),
            ),
        ]),
    ];
    let mut body = vec![0x03];
    let mut encoded = rtmpx::amf3::serialize(&values).expect("fixture AMF3 must encode");
    body.append(&mut encoded);
    Bytes::from(body)
}
