mod config;
mod errors;
mod events;
mod outstanding_transaction;
mod publish_request_type;
mod result;
mod state;

#[cfg(test)]
mod tests;

pub use self::config::ClientSessionConfig;
pub use self::errors::ClientSessionError;
pub use self::events::{ClientSessionEvent, CommandStatus};
pub use self::publish_request_type::PublishRequestType;
pub use self::result::ClientSessionResult;
pub use self::state::ClientState;

use self::outstanding_transaction::{OutstandingTransaction, TransactionPurpose};
use crate::amf::AmfEncoding;
use crate::amf0::{Amf0Object, Amf0Value};
use crate::chunk_io::{ChunkDeserializationError, ChunkDeserializer, ChunkSerializer, Packet};
use crate::messages::{RtmpMessage, UserControlEventType};
use crate::sessions::{DataMessage, DataMessageType, StreamId, StreamMetadata};
use crate::time::RtmpTimestamp;
use bytes::Bytes;
use std::collections::HashMap;
use std::mem;
use std::time::Instant;

type ClientResult = Result<Vec<ClientSessionResult>, ClientSessionError>;

/// A session that represents the client side of a single RTMP connection.
///
/// The `ClientSession` encapsulates the details of how a client interacts with a server.  This
/// includes how to connect to an application on the server, requesting publishing or playback,
/// and reacting to events and responses the server may send.
///
/// While RTMP connections can support multiple media operations simultaneously the `ClientSession`
/// has been designed for the main use case of one operation per connection.
///
/// Due to the way the header compression properties of the RTMP chunking protocol works,
/// is is required that:
///
/// * All bytes **after** the handshake has been completed are passed into the `ClientSession` in
/// the order they were received
/// * All responses generated by the session are sent to the server **in order**
/// * No extraneous bytes are passed into the session, and only bytes generated by the session are
/// sent to the server.
///
/// Any violation of these points have a high probability of causing RTMP chunk parsing errors
/// by either the `ClientSession` or the peer.
pub struct ClientSession {
    failed: bool,
    start_time: Instant,
    serializer: ChunkSerializer,
    deserializer: ChunkDeserializer,
    config: ClientSessionConfig,
    next_transaction_id: u32,
    outstanding_transactions: HashMap<u32, OutstandingTransaction>,
    current_state: ClientState,
    connected_app_name: Option<String>,
    active_stream_id: Option<u32>,
    peer_window_ack_size: Option<u32>,
    // see the matching field in `sessions/server/mod.rs`.
    self_window_ack_size: Option<u32>,
    bytes_received: u64,
    bytes_received_since_last_ack: u32,
    /// The encoding the server confirmed in its `connect` response, clamped to
    /// what this crate supports.
    negotiated_encoding: AmfEncoding,
    /// True once the server has actually used a type 15/17 message.
    peer_uses_amf3_framing: bool,
}

impl ClientSession {
    /// Whether an input error has permanently terminated this session.
    pub fn is_failed(&self) -> bool {
        self.failed
    }

    fn ensure_active(&self) -> Result<(), ClientSessionError> {
        if self.failed {
            Err(ClientSessionError::SessionFailed)
        } else {
            Ok(())
        }
    }

    /// Process bytes in transport order.
    ///
    /// Any error is terminal: close the transport and discard this session. Outputs
    /// accumulated during the failing call are discarded; no further operation may
    /// generate bytes. Successful calls return outputs in their required wire order.
    /// Caller errors from other methods (for example an invalid request ID) are not
    /// input failures and do not set this terminal state.
    pub fn handle_input(
        &mut self,
        bytes: &[u8],
    ) -> Result<Vec<ClientSessionResult>, ClientSessionError> {
        self.ensure_active()?;
        let result = self.handle_input_inner(bytes);
        if result.is_err() {
            self.failed = true;
            self.current_state = ClientState::Failed;
        }
        result
    }

    fn handle_data_message(
        &self,
        stream_id: u32,
        message: DataMessage,
    ) -> Vec<ClientSessionResult> {
        if self.active_stream_id != Some(stream_id) {
            return Vec::new();
        }
        let event = if let Ok(Some(properties)) = message.metadata() {
            let mut metadata = StreamMetadata::new();
            metadata.apply_metadata_values(properties);
            ClientSessionEvent::StreamMetadataReceived { metadata, message }
        } else {
            ClientSessionEvent::StreamDataReceived { message }
        };
        vec![ClientSessionResult::RaisedEvent(event)]
    }

    /// Creates a new client session with the specified configuration
    ///
    /// The initial output list is empty. Connection negotiation produces the
    /// required flow-control messages after the server accepts the connection.
    pub fn new(
        config: ClientSessionConfig,
    ) -> Result<(ClientSession, Vec<ClientSessionResult>), ClientSessionError> {
        if config.window_ack_size == 0 || config.chunk_size == 0 {
            return Err(ChunkDeserializationError::ResourceLimitExceeded {
                resource: "client flow-control value",
                attempted: 0,
                maximum: u32::MAX as usize,
            }
            .into());
        }
        let session = ClientSession {
            failed: false,
            start_time: Instant::now(),
            serializer: ChunkSerializer::new(),
            deserializer: ChunkDeserializer::with_config(config.chunk_deserializer),
            next_transaction_id: 1,
            outstanding_transactions: HashMap::new(),
            current_state: ClientState::Disconnected,
            active_stream_id: None,
            connected_app_name: None,
            peer_window_ack_size: None,
            self_window_ack_size: Some(config.window_ack_size),
            bytes_received: 0,
            bytes_received_since_last_ack: 0,
            negotiated_encoding: AmfEncoding::Amf0,
            peer_uses_amf3_framing: false,
            config,
        };

        let results = Vec::new();

        Ok((session, results))
    }

    /// Current state, including pending requests and terminal input failure.
    pub fn state(&self) -> &ClientState {
        &self.current_state
    }

    /// Active stream, once createStream has succeeded.
    pub fn active_stream_id(&self) -> Option<StreamId> {
        self.active_stream_id.map(StreamId::new)
    }

    /// The AMF encoding the server confirmed in its `connect` response,
    /// clamped to what this crate supports.
    ///
    /// Mirrors [`crate::sessions::ServerSession::negotiated_encoding`]. The
    /// live Red5 interop suite (`tests/red5`, feature `red5-live`) asserts on
    /// this to prove `objectEncoding` negotiation against an independent peer.
    pub fn negotiated_encoding(&self) -> AmfEncoding {
        self.negotiated_encoding
    }

    /// Takes in any number of bytes from the peer and processes them.  Any resulting responses or
    /// events are returned.
    fn handle_input_inner(&mut self, bytes: &[u8]) -> ClientResult {
        let mut results = Vec::new();
        self.bytes_received += bytes.len() as u64;

        // Acknowledge on our own advertised window when the peer
        // never advertises one. See the matching note in the server session.
        let effective_ack_size = self.peer_window_ack_size.or(self.self_window_ack_size);
        if let Some(peer_ack_size) = effective_ack_size {
            self.bytes_received_since_last_ack = self
                .bytes_received_since_last_ack
                .wrapping_add(bytes.len() as u32);
            if self.bytes_received_since_last_ack >= peer_ack_size {
                // see the matching note in `sessions/server/mod.rs`.
                // The acknowledgement sequence number is cumulative bytes
                // received, not bytes since the previous ack. Wraps at 2^32.
                let ack_message = RtmpMessage::Acknowledgement {
                    sequence_number: self.bytes_received as u32,
                };
                let ack_payload = ack_message.into_message_payload(self.get_epoch(), 0)?;
                let ack_packet = self.serializer.serialize(&ack_payload, false, false)?;

                self.bytes_received_since_last_ack %= peer_ack_size;
                results.push(ClientSessionResult::OutboundResponse(ack_packet));
            }
        }

        let mut bytes_to_process = bytes;
        loop {
            match self.deserializer.get_next_message(bytes_to_process)? {
                None => break, // no more messages
                Some(payload) => {
                    if let Some(wire_type) = DataMessageType::from_type_id(payload.type_id) {
                        if wire_type == DataMessageType::Amf3 {
                            self.peer_uses_amf3_framing = true;
                        }
                        let message = DataMessage::new(wire_type, payload.timestamp, payload.data);
                        results
                            .extend(self.handle_data_message(payload.message_stream_id, message));
                        bytes_to_process = &[];
                        continue;
                    }
                    let message = payload.to_rtmp_message()?;
                    let mut message_results = match message {
                        RtmpMessage::Abort { stream_id } => {
                            self.deserializer.abort_chunk_stream(stream_id);
                            Vec::new()
                        }
                        RtmpMessage::Acknowledgement { sequence_number } => {
                            self.handle_acknowledgement(sequence_number)?
                        }

                        RtmpMessage::Amf0Command {
                            command_name,
                            transaction_id,
                            command_object,
                            additional_arguments,
                        } => self.handle_amf0_command(
                            payload.message_stream_id,
                            command_name,
                            transaction_id,
                            command_object,
                            additional_arguments,
                        )?,

                        RtmpMessage::Amf3Command {
                            command_name,
                            transaction_id,
                            command_object,
                            additional_arguments,
                            format: _,
                        } => {
                            // Same commands, different encoding: project into
                            // the AMF0 value model and reuse the one set of
                            // handlers rather than maintaining a parallel
                            // implementation.
                            self.peer_uses_amf3_framing = true;
                            self.handle_amf0_command(
                                payload.message_stream_id,
                                command_name,
                                transaction_id,
                                command_object.to_amf0(),
                                additional_arguments.iter().map(|v| v.to_amf0()).collect(),
                            )?
                        }

                        RtmpMessage::Amf0SharedObject { data: _ }
                        | RtmpMessage::Amf3SharedObject { data: _ } => {
                            vec![ClientSessionResult::UnhandleableMessageReceived(payload)]
                        }

                        RtmpMessage::AudioData { data } => self.handle_audio_data(
                            payload.message_stream_id,
                            data,
                            payload.timestamp,
                        )?,

                        RtmpMessage::VideoData { data } => self.handle_video_data(
                            payload.message_stream_id,
                            data,
                            payload.timestamp,
                        )?,

                        RtmpMessage::UserControl {
                            event_type,
                            timestamp,
                            stream_id,
                            buffer_length,
                        } => self.handle_user_control(
                            event_type,
                            timestamp,
                            stream_id,
                            buffer_length,
                        )?,

                        RtmpMessage::WindowAcknowledgement { size } => {
                            self.handle_window_ack_size(size)?
                        }

                        RtmpMessage::SetChunkSize { size } => self.handle_set_chunk_size(size)?,

                        _ => vec![ClientSessionResult::UnhandleableMessageReceived(payload)],
                    };

                    results.append(&mut message_results);
                    bytes_to_process = &[];
                }
            }
        }

        Ok(results)
    }

    /// Forms an RTMP message requesting a connection to the specified application on the server.
    /// An event will be raised when the request is accepted or rejected.
    pub fn request_connection(
        &mut self,
        app_name: String,
    ) -> Result<ClientSessionResult, ClientSessionError> {
        self.ensure_active()?;
        // Delegate to the extensible variant so upstream behaviour is
        // preserved exactly while proxies can add their own connect properties.
        self.request_connection_with_properties(app_name, Amf0Object::new())
    }

    /// Same as `request_connection`, but merges `extra_properties` into the
    /// `connect` command object.
    ///
    /// Added for proxy use. A proxy must forward the publisher's
    /// Enhanced RTMP capability advertisement (`fourCcList`, `capsEx`,
    /// `videoFourCcInfoMap`, `audioFourCcInfoMap`) to the backend ingester.
    /// Without it an OBS 30+ publisher that negotiated HEVC or AV1 silently
    /// falls back to H.264 across the hop.
    ///
    /// Properties the session sets itself (`app`, `flashVer`, `objectEncoding`,
    /// `tcUrl`) take precedence and cannot be overridden, so a malformed or
    /// hostile connect object cannot corrupt our own session state.
    pub fn request_connection_with_properties(
        &mut self,
        app_name: String,
        extra_properties: Amf0Object,
    ) -> Result<ClientSessionResult, ClientSessionError> {
        self.ensure_active()?;
        match self.current_state {
            ClientState::Disconnected => (),
            _ => {
                return Err(ClientSessionError::CantConnectWhileAlreadyConnected);
            }
        }

        let transaction_id = self.get_next_transaction_id();
        let transaction = OutstandingTransaction::ConnectionRequested {
            app_name: app_name.clone(),
        };

        // Seed with the caller's properties, then let the session's
        // own values overwrite them.
        let mut properties = extra_properties;
        properties.insert("app".to_string(), Amf0Value::Utf8String(app_name));
        properties.insert(
            "flashVer".to_string(),
            Amf0Value::Utf8String(self.config.flash_version.clone()),
        );
        properties.insert(
            "objectEncoding".to_string(),
            Amf0Value::Number(self.config.object_encoding.as_object_encoding()),
        );

        // Some implementations require a tcUrl to be sent up with the connection request
        match &self.config.tc_url {
            Some(tc_url) => {
                properties.insert("tcUrl".to_string(), Amf0Value::Utf8String(tc_url.clone()));
            }
            None => (),
        };

        let message = RtmpMessage::Amf0Command {
            command_name: "connect".to_string(),
            command_object: Amf0Value::Object(properties),
            additional_arguments: vec![],
            transaction_id: transaction_id as f64,
        };

        let payload = message.into_message_payload(self.get_epoch(), 0)?;
        let packet = self.serializer.serialize(&payload, false, false)?;

        self.outstanding_transactions
            .insert(transaction_id, transaction);
        self.current_state = ClientState::ConnectionRequested;

        Ok(ClientSessionResult::OutboundResponse(packet))
    }

    /// Starts the process of requesting playback on the server for the specified stream key.  An
    /// event will be raised when the request is accepted or rejected.  Once accepted we will
    /// receive audio, video, and metadata information via `ClientSessionEvent`s.
    pub fn request_playback(
        &mut self,
        stream_key: String,
    ) -> Result<ClientSessionResult, ClientSessionError> {
        self.ensure_active()?;
        match self.current_state {
            ClientState::Connected => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        }

        let transaction_id = self.get_next_transaction_id();
        let transaction = OutstandingTransaction::CreateStream {
            purpose: TransactionPurpose::PlayRequest { stream_key },
        };

        let message = RtmpMessage::Amf0Command {
            command_name: "createStream".to_string(),
            transaction_id: transaction_id as f64,
            command_object: Amf0Value::Null,
            additional_arguments: Vec::new(),
        };

        let payload = message.into_message_payload(self.get_epoch(), 0)?;
        let packet = self.serializer.serialize(&payload, false, false)?;

        self.outstanding_transactions
            .insert(transaction_id, transaction);
        self.current_state = ClientState::CreatingPlayStream;

        Ok(ClientSessionResult::OutboundResponse(packet))
    }

    /// Starts the process of requesting to publish to the server on the specified stream key.  An
    /// event will be raised when the request is accepted or rejected.
    pub fn request_publishing(
        &mut self,
        stream_key: String,
        publish_type: PublishRequestType,
    ) -> Result<ClientSessionResult, ClientSessionError> {
        self.ensure_active()?;
        match self.current_state {
            ClientState::Connected => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        }

        let transaction_id = self.get_next_transaction_id();
        let transaction = OutstandingTransaction::CreateStream {
            purpose: TransactionPurpose::PublishRequest {
                stream_key,
                request_type: publish_type,
            },
        };

        let message = RtmpMessage::Amf0Command {
            command_name: "createStream".to_string(),
            transaction_id: transaction_id as f64,
            command_object: Amf0Value::Null,
            additional_arguments: Vec::new(),
        };

        let payload = message.into_message_payload(self.get_epoch(), 0)?;
        let packet = self.serializer.serialize(&payload, false, false)?;

        self.outstanding_transactions
            .insert(transaction_id, transaction);
        self.current_state = ClientState::CreatingPublishStream;

        Ok(ClientSessionResult::OutboundResponse(packet))
    }

    /// If currently playing on a stream key, this is used to tell the server we no longer want to
    /// play video from the stream.
    pub fn stop_playback(&mut self) -> ClientResult {
        self.ensure_active()?;
        if self.current_state == ClientState::CreatingPlayStream {
            self.current_state = ClientState::CancellingPlay;
            return Ok(Vec::new());
        }
        // Validate we are in a state to do this
        match self.current_state {
            ClientState::Playing { .. } => (),
            ClientState::PlayRequested { .. } => (),
            _ => return Ok(Vec::new()), // Nothing to stop since we aren't performing playback
        }

        self.current_state = ClientState::Connected;
        match mem::replace(&mut self.active_stream_id, None) {
            None => Ok(Vec::new()), // Should never happen since we should always have a valid stream id
            Some(stream_id) => {
                let message = RtmpMessage::Amf0Command {
                    command_name: "deleteStream".to_string(),
                    transaction_id: 0.0, // always 0 per spec
                    command_object: Amf0Value::Null,
                    additional_arguments: vec![Amf0Value::Number(stream_id as f64)],
                };

                let payload = message.into_message_payload(self.get_epoch(), stream_id)?;
                let packet = self.serializer.serialize(&payload, false, false)?;
                Ok(vec![ClientSessionResult::OutboundResponse(packet)])
            }
        }
    }

    /// If currently publishing on a stream key, this is used to tell the server we no longer want
    /// to publish to that stream.
    pub fn stop_publishing(&mut self) -> ClientResult {
        self.ensure_active()?;
        if self.current_state == ClientState::CreatingPublishStream {
            self.current_state = ClientState::CancellingPublish;
            return Ok(Vec::new());
        }
        // Validate we are in a state to do this
        match self.current_state {
            ClientState::Publishing { .. } => (),
            ClientState::PublishRequested { .. } => (),
            _ => return Ok(Vec::new()), // Nothing to stop since we aren't performing playback
        }

        self.current_state = ClientState::Connected;
        match mem::replace(&mut self.active_stream_id, None) {
            None => Ok(Vec::new()), // Should never happen since we should always have a valid stream id
            Some(stream_id) => {
                let message = RtmpMessage::Amf0Command {
                    command_name: "deleteStream".to_string(),
                    transaction_id: 0.0, // always 0 per spec
                    command_object: Amf0Value::Null,
                    additional_arguments: vec![Amf0Value::Number(stream_id as f64)],
                };

                let payload = message.into_message_payload(self.get_epoch(), stream_id)?;
                let packet = self.serializer.serialize(&payload, false, false)?;
                Ok(vec![ClientSessionResult::OutboundResponse(packet)])
            }
        }
    }

    /// Sends a ping request to the server.  An event will be raised when we get a response back
    pub fn send_ping_request(&mut self) -> Result<(Packet, RtmpTimestamp), ClientSessionError> {
        self.ensure_active()?;
        let current_epoch = self.get_epoch();
        let message = RtmpMessage::UserControl {
            event_type: UserControlEventType::PingRequest,
            buffer_length: None,
            stream_id: None,
            timestamp: Some(current_epoch.clone()),
        };

        let payload = message.into_message_payload(self.get_epoch(), 0)?;
        let packet = self.serializer.serialize(&payload, false, false)?;
        Ok((packet, current_epoch))
    }

    /// If publishing, this allows us to send encoder metadata to the server to send to all
    /// players.
    pub fn publish_metadata(
        &mut self,
        metadata: &StreamMetadata,
    ) -> Result<ClientSessionResult, ClientSessionError> {
        self.ensure_active()?;
        match self.current_state {
            ClientState::Publishing => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        }

        let active_stream_id = match self.active_stream_id {
            Some(x) => x,
            None => {
                return Err(ClientSessionError::NoKnownActiveStreamIdWhenRequired);
            }
        };

        let mut properties = Amf0Object::new();
        if let Some(x) = metadata.video_width {
            properties.insert("width".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.video_height {
            properties.insert("height".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.video_codec_id {
            properties.insert("videocodecid".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.video_frame_rate {
            properties.insert("framerate".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.video_bitrate_kbps {
            properties.insert("videodatarate".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.audio_codec_id {
            properties.insert("audiocodecid".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.audio_bitrate_kbps {
            properties.insert("audiodatarate".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.audio_sample_rate {
            properties.insert("audiosamplerate".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.audio_channels {
            properties.insert("audiochannels".to_string(), Amf0Value::Number(x as f64));
        }

        if let Some(x) = metadata.audio_is_stereo {
            properties.insert("stereo".to_string(), Amf0Value::Boolean(x));
        }

        if let Some(ref x) = metadata.encoder {
            properties.insert("encoder".to_string(), Amf0Value::Utf8String(x.clone()));
        }

        let message = RtmpMessage::Amf0Data {
            values: vec![
                Amf0Value::Utf8String("@setDataFrame".to_string()),
                Amf0Value::Utf8String("onMetaData".to_string()),
                Amf0Value::Object(properties),
            ],
        };

        let payload = message.into_message_payload(self.get_epoch(), active_stream_id)?;
        let packet = self.serializer.serialize(&payload, false, false)?;

        Ok(ClientSessionResult::OutboundResponse(packet))
    }

    /// Publish encoded script data, preserving its wire type, timestamp, and bytes.
    pub fn publish_data(
        &mut self,
        message: DataMessage,
    ) -> Result<ClientSessionResult, ClientSessionError> {
        self.ensure_active()?;
        if self.current_state != ClientState::Publishing {
            return Err(ClientSessionError::SessionInInvalidState {
                current_state: self.current_state.clone(),
            });
        }
        let stream_id = self
            .active_stream_id
            .ok_or(ClientSessionError::NoKnownActiveStreamIdWhenRequired)?;
        let packet =
            self.serializer
                .serialize(&message.to_message_payload(stream_id), false, false)?;
        Ok(ClientSessionResult::OutboundResponse(packet))
    }

    /// If publishing, this allows us to send video data to the server on the publishing stream.
    pub fn publish_video_data(
        &mut self,
        data: Bytes,
        timestamp: RtmpTimestamp,
        can_be_dropped: bool,
    ) -> Result<ClientSessionResult, ClientSessionError> {
        self.ensure_active()?;
        match self.current_state {
            ClientState::Publishing => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        }

        let active_stream_id = match self.active_stream_id {
            Some(x) => x,
            None => {
                return Err(ClientSessionError::NoKnownActiveStreamIdWhenRequired);
            }
        };

        let message = RtmpMessage::VideoData { data };
        let payload = message.into_message_payload(timestamp, active_stream_id)?;
        let packet = self.serializer.serialize(&payload, false, can_be_dropped)?;
        Ok(ClientSessionResult::OutboundResponse(packet))
    }

    /// If publishing, this allows us to send audio data to the server on the publishing stream.
    pub fn publish_audio_data(
        &mut self,
        data: Bytes,
        timestamp: RtmpTimestamp,
        can_be_dropped: bool,
    ) -> Result<ClientSessionResult, ClientSessionError> {
        self.ensure_active()?;
        match self.current_state {
            ClientState::Publishing => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        }

        let active_stream_id = match self.active_stream_id {
            Some(x) => x,
            None => {
                return Err(ClientSessionError::NoKnownActiveStreamIdWhenRequired);
            }
        };

        let message = RtmpMessage::AudioData { data };
        let payload = message.into_message_payload(timestamp, active_stream_id)?;
        let packet = self.serializer.serialize(&payload, false, can_be_dropped)?;
        Ok(ClientSessionResult::OutboundResponse(packet))
    }

    fn handle_video_data(
        &self,
        stream_id: u32,
        data: Bytes,
        timestamp: RtmpTimestamp,
    ) -> ClientResult {
        // PlayRequested state is allowed because some servers send video data prior to the
        // `NetStream.Play.Start` command.
        match self.current_state {
            ClientState::PlayRequested { .. } => (),
            ClientState::Playing { .. } => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        }

        // Validate we are active on the stream this message came from
        match self.active_stream_id {
            None => return Ok(Vec::new()), // not active on any stream
            Some(active_stream_id) if active_stream_id != stream_id => return Ok(Vec::new()), // not active on this stream
            Some(_) => (),
        }

        let event = ClientSessionEvent::VideoDataReceived { data, timestamp };
        Ok(vec![ClientSessionResult::RaisedEvent(event)])
    }

    fn handle_audio_data(
        &self,
        stream_id: u32,
        data: Bytes,
        timestamp: RtmpTimestamp,
    ) -> ClientResult {
        // PlayRequested state is allowed because some servers send audio data prior to the
        // `NetStream.Play.Start` command.
        match self.current_state {
            ClientState::PlayRequested { .. } => (),
            ClientState::Playing { .. } => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        }

        // Validate we are active on the stream this message came from
        match self.active_stream_id {
            None => return Ok(Vec::new()), // not active on any stream
            Some(active_stream_id) if active_stream_id != stream_id => return Ok(Vec::new()), // not active on this stream
            Some(_) => (),
        }

        let event = ClientSessionEvent::AudioDataReceived { data, timestamp };
        Ok(vec![ClientSessionResult::RaisedEvent(event)])
    }

    fn handle_amf0_command(
        &mut self,
        stream_id: u32,
        name: String,
        transaction_id: f64,
        command_object: Amf0Value,
        additional_args: Vec<Amf0Value>,
    ) -> ClientResult {
        match name.as_str() {
            "_result" => self.handle_amf0_command_success_result(
                transaction_id,
                command_object,
                additional_args,
            ),
            "_error" => self.handle_amf0_command_failed_result(
                transaction_id,
                command_object,
                additional_args,
            ),
            "onStatus" => self.handle_on_status_command(stream_id, additional_args),

            _ => {
                let event = ClientSessionEvent::UnhandleableAmf0Command {
                    stream_id: StreamId::new(stream_id),
                    command_name: name,
                    additional_values: additional_args,
                    command_object,
                    transaction_id,
                };

                Ok(vec![ClientSessionResult::RaisedEvent(event)])
            }
        }
    }

    fn handle_amf0_command_failed_result(
        &mut self,
        transaction_id: f64,
        command_object: Amf0Value,
        additional_args: Vec<Amf0Value>,
    ) -> ClientResult {
        let outstanding_transaction = match self
            .outstanding_transactions
            .remove(&(transaction_id as u32))
        {
            Some(transaction) => transaction,
            None => {
                let event = ClientSessionEvent::UnknownTransactionResultReceived {
                    additional_values: additional_args,
                    command_object,
                    transaction_id,
                };

                return Ok(vec![ClientSessionResult::RaisedEvent(event)]);
            }
        };

        let properties = additional_args
            .into_iter()
            .next()
            .and_then(|v| v.get_object_properties())
            .unwrap_or_default();
        let status = CommandStatus::new(self.active_stream_id.map(StreamId::new), properties);
        let event = match outstanding_transaction {
            OutstandingTransaction::ConnectionRequested { .. } => {
                self.current_state = ClientState::Disconnected;
                ClientSessionEvent::ConnectionRequestRejected {
                    description: status.description().unwrap_or("").to_string(),
                    status,
                }
            }
            OutstandingTransaction::CreateStream { purpose } => {
                let cancelled = matches!(
                    self.current_state,
                    ClientState::CancellingPlay | ClientState::CancellingPublish
                );
                self.current_state = ClientState::Connected;
                if cancelled {
                    return Ok(Vec::new());
                }
                match purpose {
                    TransactionPurpose::PlayRequest { .. } => {
                        ClientSessionEvent::PlaybackRequestRejected { status }
                    }
                    TransactionPurpose::PublishRequest { .. } => {
                        ClientSessionEvent::PublishRequestRejected { status }
                    }
                }
            }
        };
        Ok(vec![ClientSessionResult::RaisedEvent(event)])
    }

    fn handle_amf0_command_success_result(
        &mut self,
        transaction_id: f64,
        command_object: Amf0Value,
        additional_args: Vec<Amf0Value>,
    ) -> ClientResult {
        let outstanding_transaction = match self
            .outstanding_transactions
            .remove(&(transaction_id as u32))
        {
            Some(transaction) => transaction,
            None => {
                let event = ClientSessionEvent::UnknownTransactionResultReceived {
                    additional_values: additional_args,
                    command_object,
                    transaction_id,
                };

                return Ok(vec![ClientSessionResult::RaisedEvent(event)]);
            }
        };

        match outstanding_transaction {
            OutstandingTransaction::ConnectionRequested { app_name } => {
                self.current_state = ClientState::Connected;
                self.connected_app_name = Some(app_name);

                let message = RtmpMessage::WindowAcknowledgement {
                    size: self.config.window_ack_size,
                };
                let payload = message.into_message_payload(self.get_epoch(), 0)?;
                let packet = self.serializer.serialize(&payload, false, false)?;
                let command_object = match command_object {
                    Amf0Value::Object(properties) => properties,
                    _ => Amf0Object::new(),
                };
                let additional_properties = additional_args
                    .into_iter()
                    .next()
                    .and_then(|value| match value {
                        Amf0Value::Object(properties) => Some(properties),
                        _ => None,
                    })
                    .unwrap_or_default();
                // The server's response is the authoritative half of the
                // `objectEncoding` handshake: it states the encoding that will
                // actually be used, which may be lower than what we asked for.
                // It is clamped against our own request as well, so a server
                // answering with more than we asked for cannot push us into an
                // encoding we did not opt into.
                self.negotiated_encoding = AmfEncoding::negotiate(
                    additional_properties
                        .get("objectEncoding")
                        .and_then(|value| value.get_number())
                        .map(AmfEncoding::from_object_encoding)
                        .unwrap_or_default(),
                    self.config.object_encoding,
                );
                let event = ClientSessionEvent::ConnectionRequestAccepted {
                    command_object,
                    additional_properties,
                };

                let chunk_size_packet = self
                    .serializer
                    .set_max_chunk_size(self.config.chunk_size, RtmpTimestamp::new(0))?;

                Ok(vec![
                    ClientSessionResult::OutboundResponse(packet),
                    ClientSessionResult::RaisedEvent(event),
                    ClientSessionResult::OutboundResponse(chunk_size_packet),
                ])
            }

            OutstandingTransaction::CreateStream { purpose } => {
                if additional_args.len() == 0 {
                    return Err(ClientSessionError::CreateStreamResponseHadNoStreamNumber);
                }

                let stream_id = match additional_args[0] {
                    Amf0Value::Number(number)
                        if number.is_finite()
                            && number.fract() == 0.0
                            && number >= 1.0
                            && number <= u32::MAX as f64 =>
                    {
                        number as u32
                    }
                    _ => {
                        return Err(ClientSessionError::CreateStreamResponseHadNoStreamNumber);
                    }
                };

                if matches!(
                    self.current_state,
                    ClientState::CancellingPlay | ClientState::CancellingPublish
                ) {
                    let message = RtmpMessage::Amf0Command {
                        command_name: "deleteStream".into(),
                        transaction_id: 0.0,
                        command_object: Amf0Value::Null,
                        additional_arguments: vec![Amf0Value::Number(stream_id as f64)],
                    };
                    let payload = message.into_message_payload(self.get_epoch(), 0)?;
                    let packet = self.serializer.serialize(&payload, false, false)?;
                    self.current_state = ClientState::Connected;
                    return Ok(vec![ClientSessionResult::OutboundResponse(packet)]);
                }
                self.active_stream_id = Some(stream_id);

                match purpose {
                    TransactionPurpose::PlayRequest { stream_key } => {
                        self.current_state = ClientState::PlayRequested;

                        let buffer_message = RtmpMessage::UserControl {
                            event_type: UserControlEventType::SetBufferLength,
                            buffer_length: Some(self.config.playback_buffer_length_ms),
                            stream_id: Some(stream_id),
                            timestamp: None,
                        };

                        let buffer_payload =
                            buffer_message.into_message_payload(self.get_epoch(), 0)?;
                        let buffer_packet =
                            self.serializer.serialize(&buffer_payload, false, false)?;

                        let play_message = RtmpMessage::Amf0Command {
                            command_name: "play".to_string(),
                            transaction_id: 0.0,
                            command_object: Amf0Value::Null,
                            // Always send the `start` argument (-2 = live first, then
                            // recorded, the RTMP default). Red5 silently ignores a
                            // single-argument `play`; ffmpeg and other players always
                            // include `start`, so mirror that for interop.
                            additional_arguments: vec![
                                Amf0Value::Utf8String(stream_key),
                                Amf0Value::Number(-2.0),
                            ],
                        };

                        let play_payload =
                            play_message.into_message_payload(self.get_epoch(), stream_id)?;
                        let play_packet = self.serializer.serialize(&play_payload, false, false)?;

                        Ok(vec![
                            ClientSessionResult::OutboundResponse(buffer_packet),
                            ClientSessionResult::OutboundResponse(play_packet),
                        ])
                    }

                    TransactionPurpose::PublishRequest {
                        stream_key,
                        request_type,
                    } => {
                        self.current_state = ClientState::PublishRequested;

                        let publish_type_string = match request_type {
                            PublishRequestType::Live => "live".to_string(),
                            PublishRequestType::Record => "record".to_string(),
                            PublishRequestType::Append => "append".to_string(),
                        };

                        let publish_message = RtmpMessage::Amf0Command {
                            command_name: "publish".to_string(),
                            transaction_id: 0.0,
                            command_object: Amf0Value::Null,
                            additional_arguments: vec![
                                Amf0Value::Utf8String(stream_key),
                                Amf0Value::Utf8String(publish_type_string),
                            ],
                        };

                        let publish_payload =
                            publish_message.into_message_payload(self.get_epoch(), stream_id)?;
                        let publish_packet =
                            self.serializer.serialize(&publish_payload, false, false)?;
                        Ok(vec![ClientSessionResult::OutboundResponse(publish_packet)])
                    }
                }
            }
        }
    }

    fn handle_on_status_command(
        &mut self,
        stream_id: u32,
        arguments: Vec<Amf0Value>,
    ) -> ClientResult {
        let properties = arguments
            .into_iter()
            .next()
            .and_then(|v| v.get_object_properties())
            .ok_or(ClientSessionError::InvalidOnStatusArguments)?;
        let status = CommandStatus::new(Some(StreamId::new(stream_id)), properties);
        let code = status
            .code()
            .ok_or(ClientSessionError::InvalidOnStatusArguments)?;
        // Late statuses from deleted streams remain observable but cannot restart them.
        if self.active_stream_id != Some(stream_id) {
            return Ok(vec![ClientSessionResult::RaisedEvent(
                ClientSessionEvent::StatusReceived { status },
            )]);
        }
        let event = match code {
            "NetStream.Play.Start" if self.current_state == ClientState::PlayRequested => {
                return self.handle_play_start(status);
            }
            "NetStream.Publish.Start" if self.current_state == ClientState::PublishRequested => {
                return self.handle_publish_start(status);
            }
            "NetStream.Play.StreamNotFound"
            | "NetStream.Play.Failed"
            | "NetStream.Play.FileStructureInvalid"
            | "NetStream.Play.NoSupportedTrackFound"
                if self.current_state == ClientState::PlayRequested =>
            {
                ClientSessionEvent::PlaybackRequestRejected { status }
            }
            "NetStream.Publish.BadName"
            | "NetStream.Publish.Denied"
            | "NetStream.Publish.Failed"
                if self.current_state == ClientState::PublishRequested =>
            {
                ClientSessionEvent::PublishRequestRejected { status }
            }
            "NetStream.Play.Complete" | "NetStream.Play.Stop"
                if matches!(
                    self.current_state,
                    ClientState::Playing | ClientState::PlayRequested
                ) =>
            {
                ClientSessionEvent::PlaybackFinished { status }
            }
            "NetStream.Unpublish.Success" | "NetStream.Publish.Stop"
                if matches!(
                    self.current_state,
                    ClientState::Publishing | ClientState::PublishRequested
                ) =>
            {
                ClientSessionEvent::PublishingFinished { status }
            }
            _ if status.text("level") == Some("error")
                && self.current_state == ClientState::PlayRequested =>
            {
                ClientSessionEvent::PlaybackRequestRejected { status }
            }
            _ if status.text("level") == Some("error")
                && self.current_state == ClientState::PublishRequested =>
            {
                ClientSessionEvent::PublishRequestRejected { status }
            }
            _ => {
                return Ok(vec![ClientSessionResult::RaisedEvent(
                    ClientSessionEvent::StatusReceived { status },
                )]);
            }
        };
        // Release the server-side stream before another request can allocate a new one.
        let delete = RtmpMessage::Amf0Command {
            command_name: "deleteStream".into(),
            transaction_id: 0.0,
            command_object: Amf0Value::Null,
            additional_arguments: vec![Amf0Value::Number(stream_id as f64)],
        };
        let payload = delete.into_message_payload(self.get_epoch(), 0)?;
        let packet = self.serializer.serialize(&payload, false, false)?;
        self.current_state = ClientState::Connected;
        self.active_stream_id = None;
        Ok(vec![
            ClientSessionResult::OutboundResponse(packet),
            ClientSessionResult::RaisedEvent(event),
        ])
    }

    fn handle_play_start(&mut self, status: CommandStatus) -> ClientResult {
        match self.current_state {
            ClientState::PlayRequested => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        };

        self.current_state = ClientState::Playing;

        let event = ClientSessionEvent::PlaybackRequestAccepted { status };
        Ok(vec![ClientSessionResult::RaisedEvent(event)])
    }

    fn handle_publish_start(&mut self, status: CommandStatus) -> ClientResult {
        match self.current_state {
            ClientState::PublishRequested => (),
            _ => {
                return Err(ClientSessionError::SessionInInvalidState {
                    current_state: self.current_state.clone(),
                });
            }
        };

        self.current_state = ClientState::Publishing;
        let event = ClientSessionEvent::PublishRequestAccepted { status };
        Ok(vec![ClientSessionResult::RaisedEvent(event)])
    }

    fn handle_acknowledgement(&mut self, sequence_number: u32) -> ClientResult {
        let event = ClientSessionEvent::AcknowledgementReceived {
            bytes_received: sequence_number,
        };
        Ok(vec![ClientSessionResult::RaisedEvent(event)])
    }

    fn handle_window_ack_size(&mut self, size: u32) -> ClientResult {
        if size == 0 {
            return Err(ChunkDeserializationError::ResourceLimitExceeded {
                resource: "acknowledgement window",
                attempted: 0,
                maximum: u32::MAX as usize,
            }
            .into());
        }
        self.peer_window_ack_size = Some(size);
        Ok(Vec::new())
    }

    fn handle_user_control(
        &mut self,
        event_type: UserControlEventType,
        timestamp: Option<RtmpTimestamp>,
        _stream_id: Option<u32>,
        _buffer_length: Option<u32>,
    ) -> ClientResult {
        match event_type {
            UserControlEventType::PingRequest => self.handle_ping_request(timestamp),
            UserControlEventType::PingResponse => self.handle_ping_response(timestamp),
            _ => Ok(Vec::new()),
        }
    }

    fn handle_ping_request(&mut self, timestamp: Option<RtmpTimestamp>) -> ClientResult {
        let message = RtmpMessage::UserControl {
            event_type: UserControlEventType::PingResponse,
            buffer_length: None,
            stream_id: None,
            timestamp,
        };

        let payload = message.into_message_payload(self.get_epoch(), 0)?;
        let packet = self.serializer.serialize(&payload, false, false)?;
        Ok(vec![ClientSessionResult::OutboundResponse(packet)])
    }

    fn handle_ping_response(&mut self, timestamp: Option<RtmpTimestamp>) -> ClientResult {
        let timestamp = timestamp.unwrap_or(RtmpTimestamp::new(0));
        let event = ClientSessionEvent::PingResponseReceived { timestamp };
        Ok(vec![ClientSessionResult::RaisedEvent(event)])
    }

    fn handle_set_chunk_size(&mut self, size: u32) -> ClientResult {
        self.deserializer.set_max_chunk_size(size as usize)?;
        Ok(Vec::new())
    }

    fn get_epoch(&self) -> RtmpTimestamp {
        RtmpTimestamp::new(self.start_time.elapsed().as_millis() as u32)
    }

    fn get_next_transaction_id(&mut self) -> u32 {
        let transaction_id = self.next_transaction_id;
        self.next_transaction_id = self.next_transaction_id.wrapping_add(1);
        transaction_id
    }
}
